/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-surface-variant': '#c2c6d8',
        'surface-container-low': '#131b2e',
        'on-tertiary': '#283500',
        'surface-container-lowest': '#060e20',
        'surface-container-high': '#222a3d',
        'primary-container': '#0066ff',
        'secondary-container': '#00eefd',
        'surface-variant': '#2d3449',
        'surface-container-highest': '#2d3449',
        'surface-tint': '#b3c5ff',
        primary: '#b3c5ff',
        'on-primary': '#002b75',
        'surface-bright': '#31394d',
        'inverse-primary': '#0054d6',
        'on-surface': '#dae2fd',
        'secondary-fixed': '#81f4ff',
        'on-error-container': '#ffdad6',
        'on-primary-container': '#f8f7ff',
        surface: '#0b1326',
        'inverse-on-surface': '#283044',
        'on-error': '#690005',
        'tertiary-fixed-dim': '#abd600',
        outline: '#8c90a1',
        'inverse-surface': '#dae2fd',
        error: '#ffb4ab',
        'tertiary-container': '#617b00',
        'secondary-fixed-dim': '#00dbea',
        'surface-container': '#171f33',
        'on-background': '#dae2fd',
        'primary-fixed-dim': '#b3c5ff',
        background: '#0b1326',
        tertiary: '#abd600',
        secondary: '#d4fbff',
        'surface-dim': '#0b1326',
        'on-tertiary-container': '#f0ffbe',
        'on-secondary-container': '#00686f',
        'primary-fixed': '#dae1ff',
        'error-container': '#93000a',
        'outline-variant': '#424656',
        'on-secondary': '#00363b',
      },
      fontFamily: {
        lexend: ['Lexend', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.6' }],
        'body-md': ['16px', { lineHeight: '1.5' }],
        'body-sm': ['14px', { lineHeight: '1.5' }],
        h3: ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        h2: ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        h1: ['40px', { lineHeight: '1.2', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      spacing: {
        xs: '4px', sm: '8px', md: '16px', lg: '24px',
        xl: '40px', xxl: '64px', gutter: '24px',
      },
      borderRadius: {
        DEFAULT: '0.25rem', lg: '0.5rem', xl: '0.75rem', full: '9999px',
      },
      boxShadow: {
        glow: '0 0 12px rgba(0,102,255,0.25)',
        'glow-lg': '0 0 24px rgba(0,102,255,0.35)',
      },
    },
  },
  plugins: [],
};